# Generated by Django 4.2.4 on 2023-09-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen', models.CharField(max_length=255)),
                ('creado_por', models.IntegerField()),
            ],
        ),
    ]
