# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('tipos_catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_origen', models.CharField(max_length=255)),
                ('creado_por', models.IntegerField()),
                ('organizacion', models.ForeignKey(db_column='fk_catalogos_x_organizaciones', on_delete=django.db.models.deletion.CASCADE, to='organizaciones.organizacion')),
                ('tipo_catalogo', models.ForeignKey(db_column='fk_catalogos_x_tipos_catalogos', on_delete=django.db.models.deletion.CASCADE, to='tipos_catalogos.tipocatalogo')),
            ],
            options={
                'db_table': 'catalogos',
            },
        ),
    ]
