# Generated by Django 4.2.4 on 2023-09-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_catalogos', '0001_initial'),
        ('organizaciones', '0005_alter_organizacion_industria'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='organizacion',
            field=models.ForeignKey(db_column='fk_catalogos_x_organizaciones', default=1, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.organizacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogo',
            name='tipo_catalogo',
            field=models.ForeignKey(db_column='fk_catalogos_x_tipos_catalogos', default=1, on_delete=django.db.models.deletion.CASCADE, to='tipos_catalogos.tipocatalogo'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='catalogo',
            table='catalogos',
        ),
    ]
