# Generated by Django 4.2.4 on 2023-09-03 22:08

from django.db import migrations, models
import django.db.models.deletion
import utils.enums.industrias
import utils.enums.tamanios
import utils.enums.tiposEmpresa


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0005_alter_organizacion_industria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tamanio', models.CharField(choices=[(utils.enums.tamanios.TamanioEnum['MIC'], 'Micro'), (utils.enums.tamanios.TamanioEnum['PEQ'], 'Pequeña'), (utils.enums.tamanios.TamanioEnum['MED'], 'Mediana'), (utils.enums.tamanios.TamanioEnum['GRA'], 'Grande')], max_length=255)),
                ('industria', models.CharField(choices=[(utils.enums.industrias.IndustriasEnum['GOBERNANZA'], 'Gobernanza'), (utils.enums.industrias.IndustriasEnum['TRANSPORTACION'], 'Transportación'), (utils.enums.industrias.IndustriasEnum['SEGURIDAD'], 'Seguridad'), (utils.enums.industrias.IndustriasEnum['SOFTWARE'], 'Software'), (utils.enums.industrias.IndustriasEnum['LEGAL'], 'Legal'), (utils.enums.industrias.IndustriasEnum['LOGISTICA'], 'Logística'), (utils.enums.industrias.IndustriasEnum['SALUD'], 'Salud'), (utils.enums.industrias.IndustriasEnum['EDUCACION'], 'Educación')], max_length=255)),
                ('especialidad', models.CharField(max_length=1000)),
                ('tipo_empresa', models.CharField(choices=[(utils.enums.tiposEmpresa.TiposEmpresaEnum['COMPETENCIA'], 'Competencia'), (utils.enums.tiposEmpresa.TiposEmpresaEnum['ALIADO'], 'Aliado'), (utils.enums.tiposEmpresa.TiposEmpresaEnum['CLIENTE'], 'Cliente')], max_length=255)),
                ('creado_por', models.IntegerField()),
                ('esta_activo', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(db_column='fk_empresas_x_organizaciones', on_delete=django.db.models.deletion.CASCADE, to='organizaciones.organizacion')),
            ],
        ),
    ]
