# Generated by Django 4.2.4 on 2023-09-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metas', '0002_alter_metamodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('oportunidades', models.IntegerField()),
                ('prospectos', models.IntegerField()),
                ('ventas', models.IntegerField()),
                ('meta', models.ForeignKey(db_column='fk_trimestres_x_metas', on_delete=django.db.models.deletion.CASCADE, to='metas.metamodel')),
            ],
        ),
    ]
