# Generated by Django 4.2.4 on 2023-09-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trimestres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trimestre',
            table='trimestres',
        ),
    ]
