# Generated by Django 4.2.4 on 2023-09-03 21:46

import applications.actividades.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0003_historialproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('tipo', models.CharField(choices=[(applications.actividades.models.TiposEnum['LLAMADA'], 'Llamada'), (applications.actividades.models.TiposEnum['CORREO'], 'Correo electrónico'), (applications.actividades.models.TiposEnum['REUNION'], 'Reunión')], max_length=45)),
                ('fecha_actividad', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('hay_evento_calendar', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(db_column='fk_actividades_x_proyectos', on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
