# Generated by Django 4.2.4 on 2023-09-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
