# Generated by Django 4.2.4 on 2023-09-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_esta_activo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividad',
            table='actividades',
        ),
    ]
