# Generated by Django 4.2.4 on 2023-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embudo',
            name='esta_activo',
            field=models.CharField(default=True),
        ),
    ]
