# Generated by Django 4.2.4 on 2023-09-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embudos', '0002_embudo_esta_activo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='embudo',
            table='embudos',
        ),
    ]
