# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trimestres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunidades', models.IntegerField()),
                ('prospectos', models.IntegerField()),
                ('ventas', models.IntegerField()),
                ('trimestre', models.ForeignKey(db_column='fk_distribuciones_x_trimestres', on_delete=django.db.models.deletion.CASCADE, to='trimestres.trimestre')),
                ('user', models.ForeignKey(db_column='fk_distribuciones_x_auth_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distribuciones',
            },
        ),
    ]
