# Generated by Django 4.2.4 on 2023-09-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tamanio', models.CharField(max_length=255)),
                ('industria', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'organizaciones',
            },
        ),
    ]
