# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion
import utils.enums.industrias
import utils.enums.tamanios


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tamanio', models.CharField(choices=[(utils.enums.tamanios.TamanioEnum['MIC'], 'Micro'), (utils.enums.tamanios.TamanioEnum['PEQ'], 'Pequeña'), (utils.enums.tamanios.TamanioEnum['MED'], 'Mediana'), (utils.enums.tamanios.TamanioEnum['GRA'], 'Grande')], max_length=255)),
                ('industria', models.CharField(choices=[(utils.enums.industrias.IndustriasEnum['GOBERNANZA'], 'Gobernanza'), (utils.enums.industrias.IndustriasEnum['TRANSPORTACION'], 'Transportación'), (utils.enums.industrias.IndustriasEnum['SEGURIDAD'], 'Seguridad'), (utils.enums.industrias.IndustriasEnum['SOFTWARE'], 'Software'), (utils.enums.industrias.IndustriasEnum['LEGAL'], 'Legal'), (utils.enums.industrias.IndustriasEnum['LOGISTICA'], 'Logística'), (utils.enums.industrias.IndustriasEnum['SALUD'], 'Salud'), (utils.enums.industrias.IndustriasEnum['EDUCACION'], 'Educación')], max_length=255)),
                ('especialidad', models.CharField(max_length=1000)),
                ('esta_activo', models.BooleanField(default=True)),
                ('membresia', models.ForeignKey(db_column='fk_organizaciones_x_membresias', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membresias.membresia')),
            ],
            options={
                'db_table': 'organizaciones',
            },
        ),
    ]
