# Generated by Django 4.2.4 on 2023-09-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='membresia',
            field=models.ForeignKey(db_column='fk_organizaciones_x_membresias', null=True, on_delete=django.db.models.deletion.SET_NULL, to='membresias.membresia'),
        ),
    ]
