# Generated by Django 4.2.4 on 2023-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0002_organizacion_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
