# Generated by Django 4.2.4 on 2023-09-03 21:46

import applications.organizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_organizacion_esta_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tamanio',
            field=models.CharField(choices=[(applications.organizaciones.models.TamanioEnum['MIC'], 'Micro'), (applications.organizaciones.models.TamanioEnum['PEQ'], 'Pequeña'), (applications.organizaciones.models.TamanioEnum['MED'], 'Mediana'), (applications.organizaciones.models.TamanioEnum['GRA'], 'Grande')], max_length=255),
        ),
    ]
