# Generated by Django 4.2.4 on 2023-09-03 22:08

from django.db import migrations, models
import utils.enums.industrias


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_alter_organizacion_tamanio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='industria',
            field=models.CharField(choices=[(utils.enums.industrias.IndustriasEnum['GOBERNANZA'], 'Gobernanza'), (utils.enums.industrias.IndustriasEnum['TRANSPORTACION'], 'Transportación'), (utils.enums.industrias.IndustriasEnum['SEGURIDAD'], 'Seguridad'), (utils.enums.industrias.IndustriasEnum['SOFTWARE'], 'Software'), (utils.enums.industrias.IndustriasEnum['LEGAL'], 'Legal'), (utils.enums.industrias.IndustriasEnum['LOGISTICA'], 'Logística'), (utils.enums.industrias.IndustriasEnum['SALUD'], 'Salud'), (utils.enums.industrias.IndustriasEnum['EDUCACION'], 'Educación')], max_length=255),
        ),
    ]
