# Generated by Django 4.2.4 on 2023-09-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallesusuario',
            table='detalles_usuarios',
        ),
    ]
