# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('etapa', models.ForeignKey(db_column='fk_proyectos_x_etapas', on_delete=django.db.models.deletion.CASCADE, to='etapas.etapa')),
                ('user', models.ForeignKey(db_column='fk_proyectos_x_auth_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='HistorialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField()),
                ('dias_etapa', models.IntegerField()),
                ('proyecto', models.ForeignKey(db_column='fk_historial_proyectos_x_proyectos', on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'historial_proyectos',
            },
        ),
    ]
