# Generated by Django 4.2.4 on 2023-09-03 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0003_alter_etapa_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etapa',
            field=models.ForeignKey(db_column='fk_proyectos_x_etapas', default=1, on_delete=django.db.models.deletion.CASCADE, to='etapas.etapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='user',
            field=models.ForeignKey(db_column='fk_proyectos_x_auth_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='proyecto',
            table='proyectos',
        ),
    ]
