# Generated by Django 4.2.4 on 2023-09-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_esta_activo_proyecto_etapa_proyecto_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField()),
                ('dias_etapa', models.IntegerField()),
                ('proyecto', models.ForeignKey(db_column='fk_historial_proyectos_x_proyectos', on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
            options={
                'db_table': 'historial_proyectos',
            },
        ),
    ]
