# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('esta_activo', models.BooleanField(default=True)),
                ('embudo', models.ForeignKey(db_column='fk_etapas_x_embudos', on_delete=django.db.models.deletion.CASCADE, to='embudos.embudo')),
            ],
            options={
                'db_table': 'etapas',
            },
        ),
    ]
