# Generated by Django 4.2.4 on 2023-09-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embudos', '0002_embudo_esta_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('embudo', models.ForeignKey(db_column='fk_etapas_x_embudos', on_delete=django.db.models.deletion.CASCADE, to='embudos.embudo')),
            ],
        ),
    ]
