# Generated by Django 4.2.4 on 2023-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
