# Generated by Django 4.2.4 on 2023-09-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0002_etapa_esta_activo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etapa',
            table='etapas',
        ),
    ]
