# Generated by Django 4.2.4 on 2023-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('total_vendedores', models.IntegerField(default=0)),
                ('evento_calendario', models.BooleanField(db_column='hay_evento_calendario', default=False)),
                ('precio', models.FloatField()),
                ('esta_activo', models.BooleanField(default=True)),
                ('total_embudos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'membresias',
            },
        ),
    ]
