# Generated by Django 4.2.4 on 2023-09-04 14:25

from django.db import migrations, models
import django.db.models.deletion
import utils.enums.deciones_maker
import utils.enums.origenes
import utils.enums.puestos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255, null=True)),
                ('origen', models.CharField(choices=[(utils.enums.origenes.OrigenesEnum['DESCONOCIDO'], 'Desconocido'), (utils.enums.origenes.OrigenesEnum['BNI'], 'BNI'), (utils.enums.origenes.OrigenesEnum['BDCOMPRADA'], 'Base de datos comprada'), (utils.enums.origenes.OrigenesEnum['CAPWEBSITE'], 'Capacitación WebSite'), (utils.enums.origenes.OrigenesEnum['NETWEBINAR'], 'Networking Webinar'), (utils.enums.origenes.OrigenesEnum['REFCOLABORADOR'], 'Referido por colaborador')], max_length=255)),
                ('detalles_origen', models.CharField(max_length=1000, null=True)),
                ('es_decision_maker', models.CharField(choices=[(utils.enums.deciones_maker.DecisionesMakerEnum['SI'], 'Si'), (utils.enums.deciones_maker.DecisionesMakerEnum['NO'], 'No'), (utils.enums.deciones_maker.DecisionesMakerEnum['DESCONOCIDO'], 'Desconocido')], max_length=45)),
                ('puesto', models.CharField(choices=[(utils.enums.puestos.PuestosEnum['DESCONOCIDO'], 'Desconocido'), (utils.enums.puestos.PuestosEnum['CEO'], 'CEO'), (utils.enums.puestos.PuestosEnum['DIRECTOR'], 'Director'), (utils.enums.puestos.PuestosEnum['SOCIO'], 'Socio')], max_length=45)),
                ('esta_activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(db_column='fk_prospectos_x_empresas', on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'prospectos',
            },
        ),
    ]
